import {useEffect,useRef,useState} from 'react';
import {useLanguage} from '../context/language.js';
import {videoSource,webUrl} from '../services/api.js';
import useMedia from '../hooks/useMedia.js';
export default function VideoModal({product,onClose}){
  const {t,name}=useLanguage(),dialog=useRef(null),[failed,setFailed]=useState(false),[imageFailed,setImageFailed]=useState(false),video=useMedia(product.videoMediaId,product.videoUrl),cover=useMedia(product.coverMediaId,product.coverUrl),source=product.videoMediaId?(video.url?{type:'file',url:video.url}:null):videoSource(product.videoUrl),original=webUrl(product.videoUrl),loading=video.loading||cover.loading;
  useEffect(()=>{const node=dialog.current,previous=document.activeElement,overflow=document.body.style.overflow;node.showModal();document.body.style.overflow='hidden';return()=>{node.close();document.body.style.overflow=overflow;previous?.focus();};},[]);
  return <dialog ref={dialog} className="video-dialog" aria-labelledby="video-title" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===dialog.current){const r=dialog.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}><div className="dialog-heading"><div><small>{t('Product details')}</small><h2 id="video-title">{name(product)}</h2></div><button className="icon-button" onClick={onClose} aria-label={t('Close video')} autoFocus>×</button></div><div className="video-stage">{loading?<p role="status">{t('Loading media…')}</p>:source&&!failed?(source.type==='embed'?<iframe title={t('Watch {name}',{name:name(product)})} src={source.url} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:<video src={source.url} controls autoPlay playsInline onError={()=>setFailed(true)}/>):cover.url&&!imageFailed?<img className="detail-image" src={cover.url} alt={name(product)} onError={()=>setImageFailed(true)}/>:<div className="empty"><span>✺</span><h3>{t(failed?'Video could not be loaded':video.error||cover.error?'Local file is missing. Please upload it again.':'No media added')}</h3><p>{t(failed?'Try opening the original link.':'Contact us for product information.')}</p></div>}</div>{!loading&&(video.error||cover.error||failed)&&<p className="media-feedback">{t(failed?'Video could not be loaded':'Local file is missing. Please upload it again.')}</p>}<div className="dialog-footer"><span>{t('Make your next celebration unforgettable.')}</span>{original&&<a href={original} target="_blank" rel="noopener noreferrer">{t('Open video')} ↗</a>}</div></dialog>;
}
