import ProductFilters from '../components/ProductFilters.jsx';
import Pagination,{PageSize} from '../components/Pagination.jsx';
import {filterProducts,pageProducts} from '../services/products.js';
import {deleteMedia,mediaIds} from '../services/media.js';
import LanguageSwitch from '../components/LanguageSwitch.jsx';
import {useLanguage} from '../context/language.js';
import {useRef,useState} from 'react';
import ProductForm from '../components/ProductForm.jsx';
import {uid,webUrl,validate,phoneLink,emailLink} from '../services/api.js';
export default function AdminPage({data,onChange}){
  const {t,name}=useLanguage();
  const [category,setCategory]=useState(''),[seriesFilter,setSeriesFilter]=useState(''),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(8);
  const [tab,setTab]=useState('products'),[editing,setEditing]=useState(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState(''),[settings,setSettings]=useState(data.settings),[item,setItem]=useState({name:'',categoryId:data.categories[0]?.id||''});const importRef=useRef(null);
  function commit(next,text){onChange(next);setMessage(text);setError('');}
  function attempt(fn){try{fn();}catch(e){setError(e.message);setMessage('');}}
  function switchTab(value){setTab(value);setEditing(null);setMessage('');setError('');setItem({name:'',categoryId:data.categories[0]?.id||''});if(value==='settings')setSettings(data.settings);}
  function saveProduct(product){const previous=editing,next={...data,products:editing?.id?data.products.map(p=>p.id===product.id?product:p):[product,...data.products]};commit(next,'Product saved.');const retained=new Set(next.products.flatMap(mediaIds));deleteMedia(mediaIds(previous).filter(id=>!retained.has(id))).catch(()=>{});setEditing(null);setPage(1);}
  function removeProduct(p){if(confirm(t('Delete “{name}”?',{name:name(p)})))attempt(()=>{const next={...data,products:data.products.filter(x=>x.id!==p.id)};commit(next,'Product deleted.');const retained=new Set(next.products.flatMap(mediaIds));deleteMedia(mediaIds(p).filter(id=>!retained.has(id))).catch(()=>{});});}
  function saveItem(e){e.preventDefault();attempt(()=>{const name=item.name.trim();if(!name)throw Error('Enter a name.');if(tab==='series'&&!data.categories.some(c=>c.id===item.categoryId))throw Error('Select a category.');if(data[tab].some(x=>x.id!==item.id&&x.name.toLowerCase()===name.toLowerCase()&&(tab==='categories'||x.categoryId===item.categoryId)))throw Error('This name already exists.');const entry={...item,name,id:item.id||uid()};let products=data.products;if(tab==='series')products=products.map(p=>p.seriesId===entry.id&&p.categoryId!==entry.categoryId?{...p,seriesId:''}:p);commit({...data,products,[tab]:item.id?data[tab].map(x=>x.id===item.id?entry:x):[...data[tab],entry]},'Saved.');setItem({name:'',categoryId:item.categoryId||data.categories[0]?.id||''});});}
  function removeItem(entry){attempt(()=>{if(tab==='categories'&&(data.products.some(p=>p.categoryId===entry.id)||data.series.some(s=>s.categoryId===entry.id)))throw Error('Move or delete the products and series in this category first.');if(!confirm(t('Delete “{name}”? Products in a deleted series will be kept without a series.',{name:name(entry)})))return;commit({...data,[tab]:data[tab].filter(x=>x.id!==entry.id),products:tab==='series'?data.products.map(p=>p.seriesId===entry.id?{...p,seriesId:''}:p):data.products},'Deleted.');if(item.id===entry.id)setItem({name:'',categoryId:data.categories[0]?.id||''});});}
  function move(index,direction){const list=[...data[tab]],other=index+direction;if(other<0||other>=list.length)return;[list[index],list[other]]=[list[other],list[index]];attempt(()=>commit({...data,[tab]:list},'Order updated.'));}
  function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='firework-catalogue-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function importData(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>2*1024*1024)throw Error('Backup must be smaller than 2 MB.');const next=validate(JSON.parse(await file.text()));if(!confirm(t('Replace this browser’s catalogue with this backup?')))return;commit(next,'Backup restored.');setSettings(next.settings);setEditing(null);}catch(e){setError('Import failed. Check that this is a valid catalogue JSON backup.');}}
  function saveSettings(e){e.preventDefault();attempt(()=>{if(!settings.name.trim())throw Error('Enter a store name.');if(settings.logoUrl.trim()&&!webUrl(settings.logoUrl.trim()))throw Error('Use an HTTP or HTTPS logo URL.');if(settings.faviconUrl?.trim()&&!webUrl(settings.faviconUrl.trim()))throw Error('Use an HTTP or HTTPS icon URL.');for(const key of ['phone','whatsapp'])if(settings[key]?.trim()&&!phoneLink(settings[key],key==='whatsapp'))throw Error('Enter a valid phone or WhatsApp number with country code.');if(settings.email?.trim()&&!emailLink(settings.email))throw Error('Enter a valid email address.');commit({...data,settings:Object.fromEntries(Object.entries(settings).map(([key,value])=>[key,typeof value==='string'?value.trim():value]))},'Store settings saved.');});}
  const products=filterProducts(data.products,{category,series:seriesFilter,query,name}),paged=pageProducts(products,page,pageSize);
  return <div className="admin wrap"><header className="admin-header"><div><p className="eyebrow">{name(data.settings)} / {t('STUDIO')}</p><h1>{t("Catalogue manager")}</h1></div><div className="header-tools"><LanguageSwitch/><a className="button" href="#">{t('View catalogue')} ↗</a></div></header><div className="notice">{t("Local demo · Changes are saved only in this browser. This management page has no access protection yet.")}</div><nav className="admin-tabs" aria-label={t("Management sections")}>{['products','categories','series','settings'].map(key=><button key={key} className={tab===key?'active':''} aria-pressed={tab===key} onClick={()=>switchTab(key)}>{t(key)}</button>)}</nav>
    {message&&<p className="success" role="status">{t(message)}</p>}{error&&<p className="error" role="alert">{t(error)}</p>}
    {tab==='products'&&(editing?<ProductForm key={editing.id||'new'} product={editing.id?editing:null} categories={data.categories} series={data.series} onSave={saveProduct} onCancel={()=>setEditing(null)}/>:<section className="panel"><div className="panel-heading"><div><h2>{t("Products")} <span className="muted">({data.products.length})</span></h2><p>{t("Build your collection, one spark at a time.")}</p></div><button className="primary" onClick={()=>setEditing({})}>+ {t('New product')}</button></div><div className="admin-product-toolbar"><input className="admin-search" aria-label={t('Search products')} placeholder={t('Search products…')} value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/><ProductFilters data={data} category={category} series={seriesFilter} onCategory={value=>{setCategory(value);setSeriesFilter('');setPage(1);}} onSeries={value=>{setSeriesFilter(value);setPage(1);}}/><PageSize value={pageSize} onChange={value=>{setPageSize(value);setPage(1);}}/></div><div className="table-scroll"><table><thead><tr><th>{t("Product")}</th><th>{t("Category / Series")}</th><th>{t("Status")}</th><th>{t("Actions")}</th></tr></thead><tbody>{paged.items.map(p=><tr key={p.id}><td data-label={t('Product')}><strong>{name(p)}</strong>{!p.videoUrl&&!p.videoMediaId&&<small className="muted block">{t("Preview not added")}</small>}</td><td data-label={t('Category / Series')}>{name(data.categories.find(c=>c.id===p.categoryId))||t('Uncategorised')}<small className="muted block">{name(data.series.find(s=>s.id===p.seriesId))||t('No series')}</small></td><td data-label={t('Status')}><button className={`status ${p.visible?'visible':''}`} onClick={()=>attempt(()=>commit({...data,products:data.products.map(x=>x.id===p.id?{...x,visible:!x.visible}:x)},'Visibility updated.'))}>{t(p.visible?'Visible':'Hidden')}</button></td><td data-label={t('Actions')}><div className="actions"><button onClick={()=>setEditing(p)}>{t("Edit")}</button><button className="danger" onClick={()=>removeProduct(p)}>{t("Delete")}</button></div></td></tr>)}</tbody></table></div>{!products.length&&<p className="empty">{t('No products found.')}</p>}<Pagination total={products.length} page={paged.page} pageSize={pageSize} onChange={setPage}/></section>)}
    {['categories','series'].includes(tab)&&<div className="admin-columns"><form className="panel" onSubmit={saveItem}><h2>{t(tab==='series'?(item.id?'Edit series':'New series'):(item.id?'Edit category':'New category'))}</h2><label>{t("Name")}<input required maxLength={80} value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/></label><label>{t('English name (optional)')}<input maxLength={80} value={item.nameEn||''} onChange={e=>setItem({...item,nameEn:e.target.value})}/></label>{tab==='series'&&<label>{t("Category")}<select aria-label={t('Category')} required value={item.categoryId} onChange={e=>setItem({...item,categoryId:e.target.value})}><option value="">{t("Select category")}</option>{data.categories.map(c=><option key={c.id} value={c.id}>{name(c)}</option>)}</select></label>}<div className="actions">{item.id&&<button type="button" onClick={()=>setItem({name:'',categoryId:data.categories[0]?.id||''})}>{t("Cancel")}</button>}<button className="primary">{t(item.id?'Save changes':'Create')}</button></div></form><section className="panel"><h2 className="capitalize">{t(tab)}</h2>{data[tab].map((entry,index)=><div className="entity-row" key={entry.id}><div><strong>{name(entry)}</strong>{tab==='series'&&<small className="muted block">{name(data.categories.find(c=>c.id===entry.categoryId))}</small>}</div><div className="actions"><button disabled={!index} aria-label={t('Move {name} up',{name:name(entry)})} onClick={()=>move(index,-1)}>↑</button><button disabled={index===data[tab].length-1} aria-label={t('Move {name} down',{name:name(entry)})} onClick={()=>move(index,1)}>↓</button><button onClick={()=>setItem(entry)}>{t("Edit")}</button><button className="danger" onClick={()=>removeItem(entry)}>{t("Delete")}</button></div></div>)}{!data[tab].length&&<p className="muted">{t("Nothing added yet.")}</p>}</section></div>}
    {tab==='settings'&&<div className="admin-columns"><form className="panel settings-form" onSubmit={saveSettings}><h2>{t('Store identity')}</h2>{[['name','Store name'],['nameEn','English store name (optional)'],['tagline','Tagline'],['taglineEn','English tagline (optional)'],['logoUrl','Logo image URL'],['faviconUrl','Tab icon URL (optional)'],['tabTitle','Tab title (optional)'],['tabTitleEn','English tab title (optional)']].map(([key,label])=><label key={key}>{t(label)}<input required={key==='name'} type={key.endsWith('Url')?'url':'text'} maxLength={key.endsWith('Url')?2000:160} value={settings[key]||''} onChange={e=>setSettings({...settings,[key]:e.target.value})}/>{key==='faviconUrl'&&<small>{t('Leave blank to use the included fireworks icon.')}</small>}{key==='tabTitle'&&<small>{t('Leave blank to use the store name and fireworks catalogue title.')}</small>}</label>)}<h2 className="contact-settings-title">{t('Contact information')}</h2><p>{t('Only completed contact fields appear in the footer.')}</p>{[['phone','Phone'],['whatsapp','WhatsApp number'],['email','Email'],['address','Address'],['addressEn','English address (optional)'],['hours','Opening hours'],['hoursEn','English opening hours (optional)']].map(([key,label])=><label key={key}>{t(label)}<input type={key==='email'?'email':['phone','whatsapp'].includes(key)?'tel':'text'} maxLength={300} value={settings[key]||''} onChange={e=>setSettings({...settings,[key]:e.target.value})}/>{key==='whatsapp'&&<small>{t('Country code + number, e.g. +60…')}</small>}</label>)}<button className="primary">{t('Save settings')}</button></form><section className="panel"><h2>{t('Catalogue backup')}</h2><p className="notice">{t('JSON backup includes product details and links, not uploaded files. Keep original media files for another device.')}</p><p>{t('Export your catalogue before clearing browser data. Import a backup to restore it or transfer it to another browser.')}</p><div className="actions"><button onClick={exportData}>{t('Export JSON')}</button><button onClick={()=>importRef.current.click()}>{t('Import JSON')}</button><input ref={importRef} hidden type="file" accept=".json,application/json" onChange={importData}/></div></section></div>}
  </div>;
}
