import {useState} from 'react';
import {useLanguage} from '../context/language.js';
import LanguageSwitch from '../components/LanguageSwitch.jsx';
import ContactFooter from '../components/ContactFooter.jsx';
import ProductCard from '../components/ProductCard.jsx';
import VideoModal from '../components/VideoModal.jsx';
import ProductFilters from '../components/ProductFilters.jsx';
import Pagination,{PageSize} from '../components/Pagination.jsx';
import {filterProducts,pageProducts} from '../services/products.js';
import {webUrl} from '../services/api.js';
export default function CatalogPage({data}){
  const {t,name}=useLanguage(),[category,setCategory]=useState(''),[series,setSeries]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[logoFailed,setLogoFailed]=useState(false),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(8);
  const products=filterProducts(data.products.filter(p=>p.visible),{category,series,query,name}),paged=pageProducts(products,page,pageSize),selectedProduct=data.products.find(p=>p.id===selected&&p.visible),logo=webUrl(data.settings.logoUrl);
  function reset(){setCategory('');setSeries('');setQuery('');setPage(1);}
  return <div className="catalogue compact-catalogue" id="top"><header className="site-header wrap"><button className="brand" onClick={reset}>{logo&&!logoFailed?<img src={logo} alt="" onError={()=>setLogoFailed(true)}/>:<span className="brand-symbol" aria-hidden="true">✳</span>}<span>{name(data.settings)}<small>{t('FIREWORKS COLLECTION')}</small></span></button><div className="header-tools"><a className="contact-nav" href="#contact">{t('Contact us')}</a><LanguageSwitch/></div></header><main className="wrap"><section className="hero compact-hero"><div><h1>{t('Every celebration')} · <em>{t('spark.')}</em></h1><p>{name(data.settings,'tagline')}</p></div><span aria-hidden="true">✺</span></section><section id="collection" className="collection"><div className="section-heading"><h2>{t('Our collection')} <span>{data.products.filter(p=>p.visible).length}</span></h2></div><div className="catalogue-toolbar"><label className="search"><span aria-hidden="true">⌕</span><input aria-label={t('Search products')} placeholder={t('Search fireworks…')} value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><ProductFilters data={data} category={category} series={series} onCategory={value=>{setCategory(value);setSeries('');setPage(1);}} onSeries={value=>{setSeries(value);setPage(1);}}/><PageSize value={pageSize} onChange={value=>{setPageSize(value);setPage(1);}}/></div><p className="result-count">{t('{count} products · Click to view',{count:products.length})}</p>{products.length?<div className="product-grid">{paged.items.map((p,i)=><ProductCard key={`${p.id}-${p.coverUrl}-${p.coverMediaId||''}`} product={p} index={i} category={data.categories.find(c=>c.id===p.categoryId)} series={data.series.find(s=>s.id===p.seriesId)} onClick={()=>setSelected(p.id)}/>)}</div>:<div className="empty"><h3>{t('No products found')}</h3><p>{t('Try another category or search.')}</p><button onClick={reset}>{t('Clear filters')}</button></div>}<Pagination total={products.length} page={paged.page} pageSize={pageSize} onChange={setPage}/></section></main><ContactFooter settings={data.settings}/>{selectedProduct&&<VideoModal key={selectedProduct.id} product={selectedProduct} onClose={()=>setSelected(null)}/>}</div>;
}
